---
title: "IS 605 - Assignment 2"
author: "Raghu"
date: "September 7, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##1. Problem set 1


###(1) Show that A^T A # AA^T in general. (Proof and demonstration.)


```{r q1.1, include=TRUE}
# Sample matrix
A <- matrix(c(1,0,1,3,1,0,6,4,0), nrow = 3, byrow = T)
A

# Transpose of matrix A
t(A)

# Transposed matrix A multiplied by  matrix A 
TAA <- t(A) %*% A

TAA

# Matrix A multiplied by transposed matrix A (A^T)
ATA <- A %*% t(A)
ATA

# So, A^T.A != A.A^T.

TAA == ATA

```

###(2) For a special type of square matrix A, we get AT A = AAT . Under what conditions
###could this be true? (Hint: The Identity matrix I is an example of such a matrix).


```{r q1.2, include=TRUE}
# Sample matrix
A <- matrix(c(5,2,4,2,0,2,4,2,5), nrow = 3, byrow = T)
A

# Transpose of matrix A
t(A)

# Transposed matrix A multiplied by  matrix A 
TAA <- t(A) %*% A

TAA

# Matrix A multiplied by transposed matrix A (A^T)
ATA <- A %*% t(A)
ATA

# So, A^T.A != A.A^T.

TAA == ATA

#Since the example is an identity matrix, the condition is TRUE

```


##2. Problem set 2

###Write an R function to factorize a square matrix A into LU or LDU


```{r q2, include=TRUE}

#Declare the function
factorize <- function(A) {

#Check size of matrix - first 2x2, 3x3
if (nrow(A) == 2) {

  #2x2 matrix

  #Subract multipler R21
  R21 <- -A[2,1] / A[1,1]
  L <- matrix(c(1,0,R21,1),nrow=2, byrow = T)
  U <- L %*% A
  #U

  print("###A###")
  print(A)
  print("###L###")
  print(L)
  print("###U###")
  print(U)

  L <- solve(L)
  #Inverse of L
  print("###Inverse of L ###")
  print(L)
  (L %*% U == A)

} else if (nrow(A) == 3) {

  #3x3 matrix

  #Subract multipler R21
  R21 <- -A[2,1] / A[1,1]
  mR21 <- matrix(c(1,0,0,R21,1,0,0,0,1), nrow=3, byrow = T)
  A2 <- mR21 %*% A
  #A2

  #Subract multipler E31
  R31 <- -A2[3,1] / A2[1,1]
  mR31 <- matrix(c(1,0,0,0,1,0,R31,0,1), nrow=3, byrow = T)
  A3 <- mR31 %*% A2
  #A3

  #Subtract multipler E32
  R32 <- -A3[3,2] / A3[2,2]
  mR32 <- matrix(c(1,0,0,0,1,0,0,R32,1), nrow=3, byrow = T)
  U <- mR32 %*% A3
  
  L <- solve(mR21) %*% solve(mR31) %*% solve(mR32)
  A <- L %*% U
  

  print("###A###")
  print(A)
  print("###L###")
  print(L)
  print("###U###")
  print(U)
  
  
  (L %*% U == A)

}}

#Check with 2x2 matrix

A <- matrix(c(2,3,6,8),nrow=2, byrow = T)
factorize(A)

#Check with 3x3 matrix

A <- matrix(c(2,3,6,8,2,1,0,3,1),nrow=3, byrow = T)
factorize(A)

```